### ISSUE TITLE
color setting for 'visited link'

### ISSUE THREAD

**Issue by aj3423** [satorioh/google-enhancer#3]
By default, google searching result uses a different color for visited link. But Google Enhancer uses a very close color that make it too difficult to identify if a link is visited. A configurable color setting would be great.
![1](https://user-images.githubusercontent.com/4710875/44006306-ff8e4fb2-9eb4-11e8-8aea-74f9a29b3a5d.png)

**Comment by satorioh** [comment]
v1.1.3 fixed
