### ISSUE TITLE
浮动搜索框 这个选项与谷歌搜索冲突

### ISSUE THREAD

**Issue by fhefh2015** [satorioh/google-enhancer#5]
谷歌搜索 现在的搜索框已经可以滚动固定了  将插件选项打开后 用户体验不好~ 作者可以看看~

**Comment by satorioh** [comment]
> 谷歌搜索 现在的搜索框已经可以滚动固定了 将插件选项打开后 用户体验不好~ 作者可以看看~

感谢提醒，年后会考虑重构一版，届时一并解决。

**Comment by satorioh** [comment]
v1.1.1 已移除相关选项
