### ISSUE TITLE
Card view layout broken for certain container types

### ISSUE THREAD

**Issue by reruem** [satorioh/google-enhancer#7]
Basically just look at the picture, there are other examples you can easily find doing different searches where the content extends beyond the card style

![Snipaste_2020-03-26_03-10-17](https://user-images.githubusercontent.com/58284478/77635303-94cee100-6f0f-11ea-9482-bf4052b7fd1a.png)

**Comment by satorioh** [comment]
@reruem thanks for your feedback, I will try to fix it this week,and update a new version later

**Comment by satorioh** [comment]
@reruem the new version 1.1.2 had been released, I made some optimization for card view, you can try it to see if  the problem solved.

**Comment by satorioh** [comment]
v1.1.2 fixed
