### ISSUE TITLE
can't mark  search term with double click

### ISSUE THREAD

**Issue by Wawuschel** [satorioh/google-enhancer#8]
Hi,
I cannot select a search term in the search bar by double-clicking

see my screencast as gif animation
![Gif-Animation 2020-04-10 18-41-31](https://user-images.githubusercontent.com/8377249/79007663-edcb8580-7b5b-11ea-86d6-5e10229cf56b.gif)

Windows 10
Vivaldi | 2.11.1811.52 (Stable channel) (64-Bit)

**Comment by Wawuschel** [comment]
... after I switch off the option "Double click back to top", double click to mark a word is working now.

![2020 04 10-18 51 27 - ikbcccnfbfobgioefgaodgmnnnbjbbfn](https://user-images.githubusercontent.com/8377249/79007905-86620580-7b5c-11ea-8dd7-4b32d2c83306.png)

**Comment by satorioh** [comment]
@Wawuschel thanks for your feedback, I will try to fix on next version.Due to COVID-19 impact, there may be some delays for Chrome Store to verify the new version

**Comment by satorioh** [comment]
v1.1.3 fixed
